$(function(){$.extend({sc_ID:"id_"+Math.round(1E5*Math.random()),sc_API:"http://takahamalifeart.com/weblib/api/gadget.php",schedule:{order:"0000-00-00",ship:"0000-00-00",deli:"0000-00-00"},workday:4,deliveryday:1,dayOff:[0,0,0,0,0,0,0,0],holiday:{},updateCalendar:function(a,b){var d=0;$(".schedule_calendar tbody td .material-icons.is-selected").is(".is-appeared")&&(d=1);var f=$.getToday();12<b?(a++,b=1):1>b&&(a--,b=12);$.ajax({url:$.sc_API+"?callback=?",async:!0,type:"GET",dataType:"jsonp",data:{act:"delivery",
y:a,m:b,orderdate:$.schedule.order,mode:d}}).done(function(a){var b=$("#"+$.sc_ID);$.each(a,function(a,d){var e=d.month-0,e='<div class="flex-container"><div><ins class="sc_year">'+d.year+'</ins><span>\u5e74</span><ins class="sc_month">'+d.month+'</ins><span>\u6708</span></div><div class="mdl-layout-spacer"></div><div><button class="mdl-button mdl-js-button mdl-button--icon" onclick="$.updateCalendar('+d.year+","+(e-1)+');"><i class="material-icons">&#xE408;</i></button><button class="mdl-button mdl-js-button" onclick="$.updateCalendar('+
f.y+","+f.m+');"><span>\u4eca\u65e5</span></button><button class="mdl-button mdl-js-button mdl-button--icon" onclick="$.updateCalendar('+d.year+","+(e+1)+');"><i class="material-icons">&#xE409;</i></button></div></div>';b.find("caption").html(e);b.find("tbody").html(d.schedule.calendar).promise().done(function(){$.ripple()})})})},reschedule:function(a,b){orderdate=3==arguments.length?arguments[2]:$.schedule.order;$.ajax({url:$.sc_API+"?callback=?",async:!0,type:"GET",dataType:"jsonp",data:{act:"delivery",
y:a,m:b,orderdate:orderdate}}).done(function(a){var b=$("#"+$.sc_ID);$.each(a,function(a,c){b.find("tbody").html(c.schedule.calendar).promise().done(function(){$.ripple()});$.schedule.order=c.schedule.order;$.schedule.ship=c.schedule.ship;$.schedule.deli=c.schedule.delivery});$.setSchedule()})},ripple:function(){var a,b,d,f;$(".ripplable").on("click",function(e){var c=$(this);if(c.children(".material-icons").is(".is-appeared"))return $.switchHoliday(c),!1;0===c.find(".ink").length&&c.prepend("<span class='ink'></span>");
a=c.find(".ink");a.removeClass("animate");a.height()||a.width()||(b=Math.max($(this).outerWidth(),c.outerHeight()),a.css({height:b,width:b}));d=e.pageX-c.offset().left-a.width()/2;f=e.pageY-c.offset().top-a.height()/2;e=$("#"+$.sc_ID);var g=e.find(".sc_year").text(),k=e.find(".sc_month").text();e=c.children("ins").text();var h=k,l=g;c.hasClass("pass")?1==k?(--l,h=12):--h:c.hasClass("yet")&&(12==k?(++l,h=1):++h);var m=l+"-"+h+"-"+e;a.css({top:f+"px",left:d+"px"}).addClass("animate").promise().done(function(){$.reschedule(g,
k,m)})})},switchHoliday:function(a){var b=$("#"+$.sc_ID),d=b.find(".sc_year").text(),b=b.find(".sc_month").text();a=a.find(".is-selected");var f=a.removeClass("is-selected is-appeared").siblings(".material-icons").addClass("is-selected is-appeared").siblings("ins").text(),d=$.formatDate(d+"-"+b+"-"+f,"YYYY-MM-DD");$.holiday[d]=a.is(".dayoff")?0:1},updateUser:function(){var a={user_id:"0",workday:$.workday,deliveryday:$.deliveryday,onsundays:$.dayOff[0],onmondays:$.dayOff[1],ontuesdays:$.dayOff[2],
onwednesdays:$.dayOff[3],onthursdays:$.dayOff[4],onfridays:$.dayOff[5],onsaturdays:$.dayOff[6],onholidays:$.dayOff[7],holiday:JSON.stringify($.holiday)};$.ajax({url:$.sc_API+"?callback=?",async:!0,type:"GET",dataType:"jsonp",data:{act:"update",args:a}}).done(function(a){var d=$("#"+$.sc_ID);a=d.find(".sc_year").text();d=d.find(".sc_month").text();$.reschedule(a,d)})},getToday:function(){var a=new Date,b=a.getFullYear(),d=a.getMonth()+1,a=a.getDate();return{y:b,m:d,d:a}},formatDate:function(a,b){a=
new Date(a);b||(b="YYYY-MM-DD hh:mm:ss.SSS");b=b.replace(/YYYY/g,a.getFullYear());b=b.replace(/MM/g,("0"+(a.getMonth()+1)).slice(-2));b=b.replace(/DD/g,("0"+a.getDate()).slice(-2));b=b.replace(/hh/g,("0"+a.getHours()).slice(-2));b=b.replace(/mm/g,("0"+a.getMinutes()).slice(-2));b=b.replace(/ss/g,("0"+a.getSeconds()).slice(-2));if(b.match(/S/g))for(var d=("00"+a.getMilliseconds()).slice(-3),f=b.match(/S/g).length,e=0;e<f;e++)b=b.replace(/S/,d.substring(e,e+1));return b}});(function(a){var b=a.getToday();
a.when(a.ajax({url:a.sc_API+"?callback=?",async:!0,type:"GET",dataType:"jsonp",data:{act:"delivery"}})).then(function(d){var f="";a.each(d,function(d,c){var g=c.month-0;f+='<table class="schedule_calendar"><caption><div class="flex-container"><div><ins class="sc_year">'+c.year+'</ins><span>\u5e74</span><ins class="sc_month">'+c.month+'</ins><span>\u6708</span></div><div class="mdl-layout-spacer"></div><div><button class="mdl-button mdl-js-button mdl-button--icon" onclick="$.updateCalendar('+c.year+
","+(g-1)+');"><i class="material-icons">&#xE408;</i></button><button class="mdl-button mdl-js-button" onclick="$.updateCalendar('+b.y+","+b.m+');"><span>\u4eca\u65e5</span></button><button class="mdl-button mdl-js-button mdl-button--icon" onclick="$.updateCalendar('+c.year+","+(g+1)+');"><i class="material-icons">&#xE409;</i></button></div></div></caption><thead><tr><td class="sun">\u65e5</td><td>\u6708</td><td>\u706b</td><td>\u6c34</td><td>\u6728</td><td>\u91d1</td><td class="sat">\u571f</td></tr></thead><tbody>'+
c.schedule.calendar+"</tbody></table>";a.schedule.order=c.schedule.order;a.schedule.ship=c.schedule.ship;a.schedule.deli=c.schedule.delivery;a.workday=c.schedule.workday;a.deliveryday=c.schedule.deliveryday;a.dayOff=c.schedule.dayoff});a("head").append("<link>");a("head link:last").attr({rel:"stylesheet",type:"text/css",media:"screen",href:"http://takahamalifeart.com/weblib/calendar/delivery_calendar.css"});a(".schedule_calendar_wrap").attr("id",a.sc_ID).html(f).promise().done(function(){a.ripple();
"function"==typeof a.setSchedule&&a.setSchedule();"function"==typeof a.setHolidaySetting&&a.setHolidaySetting()})})})(jQuery)});